CFLAGS=-Werror -Wall -O2
INCLUDES=-I./
LIB_INCLUDES=-L./

TEST=greshunkel_test
NAME=libgshkl.so


all: $(TEST) $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -fPIC -c $<

clean:
	rm -f *.o
	rm -f $(TEST)
	rm -f $(NAME)

greshunkel_test: greshunkel_test.o $(NAME)
	$(CC) $(CLAGS) $(LIB_INCLUDES) $(INCLUDES) -o $(TEST) $^ -lgshkl

$(NAME): greshunkel.o
	$(CC) $(CLAGS) $(INCLUDES) -shared -o $(NAME) $^
